# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-05 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwaretype',
            name='image',
        ),
    ]
