# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_remove_hardwaretype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaretype',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
